import { reactive } from "vue";

export const VIEW_KEYS = ["workbench", "library", "assessment", "settings"];

export function createInitialState() {
  return {
    currentView: "workbench",
    projects: [],
    selectedProjectId: "",
    projectsLoading: false,
    projectLoadError: "",
    projectFormSubmitting: false,
    projectFormError: "",
    projectRenameSubmitting: false,
    projectDeleteSubmitting: false,
    projectMutationError: "",
    projectMutationStatus: "",
    importSubmitting: false,
    importError: "",
    importStatus: "",
    importPreview: null,
    importPreviewLoading: false,
    importPreviewError: "",
    currentQuestion: "",
    answerResult: null,
    answerLoading: false,
    answerError: "",
    answerStatus: "等待提问",
    documents: [],
    documentsLoading: false,
    documentsLoadError: "",
    selectedDocumentId: "",
    selectedDocument: null,
    documentPreviewLoading: false,
    documentPreviewError: "",
    chatMessages: [],
    chatSessions: [],
    selectedChatSessionId: "",
    promptPresets: [],
    promptPresetTemplates: [],
    selectedPromptPresetId: "",
    editingPromptPresetId: "",
    promptPresetsLoading: false,
    promptPresetLoadError: "",
    promptPresetSubmitting: false,
    promptPresetDeletingId: "",
    promptPresetDefaultSubmitting: false,
    promptPresetMutationError: "",
    promptPresetStatus: "",
    documentCollections: [],
    selectedDocumentCollectionId: "",
    documentCollectionsLoading: false,
    documentCollectionsLoadError: "",
    collectionFormSubmitting: false,
    collectionFormError: "",
    collectionFormStatus: "",
    collectionRenameSubmitting: false,
    collectionRenameError: "",
    collectionRenameStatus: "",
    deletingCollectionId: "",
    collectionItemSubmittingId: "",
    collectionItemError: "",
    collectionItemStatus: "",
    deletingDocumentId: "",
    documentDeleteError: "",
    documentDeleteStatus: "",
    importBatches: [],
    importBatchesLoading: false,
    importBatchesLoadError: "",
    selectedImportBatch: null,
    selectedImportBatchItems: [],
    importBatchDetailLoading: false,
    importBatchDetailError: "",
    modelProfiles: [],
    defaultModelProfileId: "",
    llmSettings: {},
    llmSettingsLoading: false,
    llmSettingsSubmitting: false,
    llmSettingsTesting: false,
    llmSettingsError: "",
    llmSettingsStatus: "",
    modelProfilesLoading: false,
    modelProfileLoadError: "",
    modelProfileSubmitting: false,
    modelProfileTestingId: "",
    modelProfileDeletingId: "",
    modelProfileDefaultSubmitting: false,
    modelProfileMutationError: "",
    modelProfileStatus: "",
    editingModelProfileId: "",
    lastAnswerMessageId: "",
    agentTools: [],
    agentToolRuns: [],
    selectedAgentToolRun: null,
    documentFilter: "",
    assessmentSession: null,
    assessmentQuestion: null,
    currentToolSuggestion: null,
    currentToolContextRunId: "",
    currentAnswerAbortController: null,
    lastUsableToolRun: null,
    searchDebugResult: null,
    retrievalReviews: [],
    selectedRetrievalReview: null,
    projectSummary: null,
    retrievalSettings: null,
    assessmentQuestionIndex: 0,
    assessmentResults: [],
    assessmentMissedQuestions: [],
    assessmentAnsweredCurrent: false,
    assessmentLoading: false,
    assessmentSubmitting: false,
    assessmentError: "",
    assessmentStatus: "等待评估",
  };
}

export const appState = reactive(createInitialState());

export function showView(view) {
  if (!VIEW_KEYS.includes(view)) {
    return;
  }
  appState.currentView = view;
}
